import React from 'react';
import { useEffect } from 'react';
import styles from '../styles/component_styles/sizeGrid.module.scss';

const SizeGrid = ({ close }) => {   
    return (
        <div className={styles.sizeGrid} onClick={() => close(false)}>
            <div className={styles.sizeGrid__wrapper} onClick={e => e.stopPropagation()}>
                <h1 className={styles.sizeGrid__title}>Размерная сетка</h1>
                <div className={styles.sizeGrid__btn_close} onClick={() => close(false)}></div>
                <div className={styles.sizeGrid__table_container}>
                    <table className={styles.sizeGrid__table}>
                        <thead>
                            <th scope="col">US</th>
                            <th scope="col">UK</th>
                            <th>EUR</th>
                            <th>RUS</th>
                            <th>CM</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>4</td>
                                <td>3.5</td>
                                <td>36</td>
                                <td>35</td>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>4.5</td>
                                <td>4</td>
                                <td>36.5</td>
                                <td>35.5</td>
                                <td>23.5</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>4.5</td>
                                <td>37.5</td>
                                <td>36.5</td>
                                <td>23.5</td>
                            </tr>
                            <tr>
                                <td>5.5</td>
                                <td>5</td>
                                <td>38</td>
                                <td>37</td>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>5.5</td>
                                <td>38.5</td>
                                <td>37.5</td>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>6.5</td>
                                <td>6</td>
                                <td>39</td>
                                <td>38</td>
                                <td>24.5</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>6</td>
                                <td>40</td>
                                <td>39</td>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>7.5</td>
                                <td>6.5</td>
                                <td>40.5</td>
                                <td>39.5</td>
                                <td>25.5</td>
                            </tr>
                            <tr>
                                <td>8</td>
                                <td>7</td>
                                <td>41</td>
                                <td>40</td>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>8.5</td>
                                <td>7.5</td>
                                <td>42</td>
                                <td>41</td>
                                <td>26.5</td>
                            </tr>
                            <tr>
                                <td>9</td>
                                <td>8</td>
                                <td>42.5</td>
                                <td>41.5</td>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>9.5</td>
                                <td>8.5</td>
                                <td>43</td>
                                <td>42</td>
                                <td>27.5</td>
                            </tr>
                            <tr>
                                <td>10</td>
                                <td>9</td>
                                <td>44</td>
                                <td>43</td>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>10.5</td>
                                <td>9.5</td>
                                <td>44.5</td>
                                <td>43.5</td>
                                <td>28.5</td>
                            </tr>
                            <tr>
                                <td>11</td>
                                <td>10</td>
                                <td>45</td>
                                <td>44</td>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>11.5</td>
                                <td>10.5</td>
                                <td>45.5</td>
                                <td>44.5</td>
                                <td>29.5</td>
                            </tr>
                            <tr>
                                <td>12</td>
                                <td>11</td>
                                <td>46</td>
                                <td>45</td>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>12.5</td>
                                <td>11.5</td>
                                <td>47</td>
                                <td>46</td>
                                <td>30.5</td>
                            </tr>
                            <tr>
                                <td>13</td>
                                <td>12</td>
                                <td>47.5</td>
                                <td>46.5</td>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>13.5</td>
                                <td>12.5</td>
                                <td>48</td>
                                <td>47</td>
                                <td>31.5</td>
                            </tr>
                            <tr>
                                <td>14</td>
                                <td>13</td>
                                <td>48.5</td>
                                <td>47.5</td>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>15</td>
                                <td>14</td>
                                <td>49.5</td>
                                <td>48.5</td>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>16</td>
                                <td>15</td>
                                <td>50.5</td>
                                <td>49.5</td>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>17</td>
                                <td>16</td>
                                <td>51.5</td>
                                <td>50.5</td>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>18</td>
                                <td>17</td>
                                <td>52.5</td>
                                <td>51.5</td>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>XS</td>
                                <td>4.5-6</td>
                                <td>37.5-40</td>
                                <td>36.5-39</td>
                                <td>23.5-25</td>
                            </tr>
                            <tr>
                                <td>S</td>
                                <td>6-8</td>
                                <td>40-42.5</td>
                                <td>39-41.5</td>
                                <td>25-27</td>
                            </tr>
                            <tr>
                                <td>M</td>
                                <td>8-10</td>
                                <td>42.5-45</td>
                                <td>41.5-44</td>
                                <td>27-29</td>
                            </tr>
                            <tr>
                                <td>L</td>
                                <td>10-12</td>
                                <td>45-47.5</td>
                                <td>44-46.5</td>
                                <td>29-31</td>
                            </tr>
                            <tr>
                                <td>XL</td>
                                <td>12-14</td>
                                <td>47.5-49.5</td>
                                <td>46.5-48.5</td>
                                <td>31-33</td>
                            </tr>
                            <tr>
                                <td>XXS</td>
                                <td>2.5-4.5</td>
                                <td>35-37.5</td>
                                <td>34-36.5</td>
                                <td>22-23.5</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    );
};

export default SizeGrid;